[project]
authors = ["abrahimzaman360 <AbrahimZaman3@gmail.com>"]
channels = ["conda-forge"]
name = "Train-Python"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
hello = "python hello-pixi.py"

[dependencies]
python = "3.12.*"
